//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manage.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tuananhEntities : DbContext
    {
        public tuananhEntities()
            : base("name=tuananhEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<coursecategory> coursecategories { get; set; }
        public virtual DbSet<coursedetail> coursedetails { get; set; }
        public virtual DbSet<enrollment> enrollments { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<topic> topics { get; set; }
        public virtual DbSet<trainee> trainees { get; set; }
        public virtual DbSet<trainer> trainers { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
